### ISSUE TITLE
Hey, so... I'm making a html2ijk thingy...

### ISSUE THREAD

**Issue by slacktracer** [lukejacksonn/xyzd#16]
I've been using ijk for a little while and right now I think it is the best way to "write" HTML. \o/

But I also love _copy & paste_. =P

So I'm writing this thing so I can turn HTML into ijk: https://github.com/slacktracer/lmn.

I guess I'm asking... Is that OK with you?

Anyway, thank you very.

By the way, we must start campaigning to get ijk as one of the alternatives for JSX on the hyperapp readme sooner than later. =D

**Comment by lukejacksonn** [comment]
Glad you like it 😅 and of course that is ok! Sounds like a great idea. Let me know when you are done with it and I will try it out.

By the react readme I guess you mean somewhere like here https://reactjs.org/docs/react-without-jsx.html maybe it is worth an ask.. but I haven't actually tried it with react yet. Have you?

**Comment by slacktracer** [comment]
No, sorry, I said the hyperapp readme. 😅 I've been using hyperapp and ijk as much as I can. 😄

**Comment by slacktracer** [comment]
Specifically, this part: "Note that JSX is not required for building applications with Hyperapp. You can use hyperapp.h directly and without a compilation step as shown above. Other alternatives to JSX include @hyperapp/html, hyperx and t7."

Perhaps a PR? 😅😊

**Comment by slacktracer** [comment]
@lukejacksonn 

Just so you know, it seems to be working so I'll start using it and see how it goes.

https://slacktracer.github.io/lmn/

Thank you very much! =)

(In case you actually check the link: It's awful, I know... Awful...)

**Comment by lukejacksonn** [comment]
Ahh I misunderstood your README comment. I will think about a PR to hyperapp.

Your project though.. is not awful, It is pretty freaking cool if you ask me! We could polish it up a bit with some css 💅 but the functionality looks right. Until now there has been no way to do this and it is a useful function to have around in the ijk world.

When I get time, I will try and PR some styling. Great work man!
