### ISSUE TITLE
Exception is thrown when running with Hyperapp

### ISSUE THREAD

**Issue by zvchei** [lukejacksonn/xyzd#18]
Hi!

Running the [Hyperapp demo](https://codepen.io/lukejacksonn/pen/BJvXvg?editors=0010) throws the exception `TypeError: Cannot assign to read only property '0' of string 'Hello World'`.

Versions of the libraries: 
* hyperapp: 1.2.5
* ijk: 0.22.0

**Comment by lukejacksonn** [comment]
Hummmm.. that is weird. All tests are still passing and the preact demo works with `0.22.0` see [here](https://codepen.io/lukejacksonn/pen/ZvwKva). I will take a look into this now!

**Comment by lukejacksonn** [comment]
It seems like this is an issue with hyperapp `>1.1.0` whereby the `children` prop on a vdom node can no longer be a string. I have pinned the hyperapp version in the codepen to `1.1.0` until we resolve the issue. Feel free to join/follow the discussion on hyperapp slack or open an issue on the hyperapp repo.

Thanks for the report 🙇

**Comment by lukejacksonn** [comment]
This has been fixed by #19 the demo is [working again](https://codepen.io/lukejacksonn/pen/BJvXvg?editors=0010) 🎉 thanks @svetos1av!
