### ISSUE TITLE
Support emmet-style tags?

### ISSUE THREAD

**Issue by foxdonut** [lukejacksonn/xyzd#21]
Hi @lukejacksonn!

Thank you for this project! I am hoping to experiment with it as a way to write views in a virtual-Dom library independent way, so I hope you continue to support being able to specify the node structure and not just preact and hyperapp.

I have done an experiment with JSX here: https://meiosis.js.org/examples/setup 

But I think an ijk/hyperscript version would be even cooler! I will give it a try.

Now, I was thinking, would it make sense to support emmet style tags such as `["button#save.btn.btn-primary", ...]`? I suppose you would also have to have a way to specify whether to use `class` or `className`, not sure...

What do you think?

Thank you!

**Comment by lukejacksonn** [comment]
Hey 👋 thanks for getting involved! I do intend to keep the schema configurable (for now at least) perhaps at some point I might export a few _framework ready_ functions that are already configured but I haven't found a super nice way to do it yet.

I actually have a version somewhere that does what you have requested.. but I can't find it right now. It might have been a bad implementation but I don't remember it being too big of a change (~5LOC)! I'd like to see how you would go about it if you have any bright ideas.

**Comment by foxdonut** [comment]
I ended up getting a little bit carried away, perhaps :-) and wrote [seview](https://github.com/foxdonut/seview). Thanks for the inspiration @lukejacksonn !

**Comment by lukejacksonn** [comment]
Wow. So you did! Looks great 🎉
