### ISSUE TITLE
Tags as  functions 

### ISSUE THREAD

**Issue by yonatanmn** [lukejacksonn/xyzd#7]
Looks cool 
Here's an idea:
Instead of strings for tag names use a set of functions so proper typing will provide auto complete and error throwing

```js
Import { dom } from 'ijk'

const tree = h('name', 'props', 'children')(
  ['main', [
    [dom.h1( 'Hello World')]
  
    [dom.button({ onclick: console.log }, 'Log event ']
)
```

**Comment by lukejacksonn** [comment]
This is similar to what already exists already in a package like https://github.com/hyperapp/html which I really like and would recommend. But the idea behind this syntax is that you don't have to depend on (have to import) all the individual functions. This proposal defeats that point.

**Comment by lukejacksonn** [comment]
Closing here, let me know if you have any other thoughts! 🙇
